main := "main"
compiler := "pdflatex"
build_dir := "build"
figs_dir := "build/figures"

default: build

build: ensure-dirs
    latexmk -pdf -pdflatex="{{compiler}} %O %S" -synctex=1 -interaction=nonstopmode {{main}}.tex -output-directory={{build_dir}} -shell-escape

watch: ensure-dirs
    latexmk -pvc -pdf -pdflatex="{{compiler}} %O %S" -synctex=1 -interaction=nonstopmode {{main}}.tex -output-directory={{build_dir}} -shell-escape

clear:
    latexmk -C --\output-directory="{{build_dir}}"

ensure-dirs:
    mkdir -p {{figs_dir}}
