#!/usr/bin/env bash

bt() {
    if (( $# != 2 )); then
        echo -e "${YELLOW}Usage:${NC} bt [(dis/re)connect] [DEVICE]"
        return 1
    fi

    declare -A device=(
        ["jbl"]='84:D3:52:4D:1E:E3'
        ["edi"]='CC:14:BC:9B:A4:47'
        ["mxv"]='D6:4F:84:19:E7:02')

    local audio_device=(
        "jbl"
        "edi"
    )

    local CMD=$(echo  $1 | tr '[:upper:]' '[:lower:]')
    local DEV_NAME=$(echo  $2 | tr '[:lower:]' '[:upper:]')
    local DEV=$(echo  $2 | tr '[:upper:]' '[:lower:]')
    local PACTL_DEV=$(echo $device[$DEV] | tr ':' '_')

    case $CMD in
        "c" | "connect")
            MSG="connect"
            bluetoothctl connect ${device[${DEV}]} &> /dev/null
            if [[ $audio_device[*] =~ $DEV ]]; then
                echo "Change audio out"
                pactl set-default-sink "bluez_output.$PACTL_DEV.1"
            fi
        ;;
        "d" | "disconnect")
            MSG="disconnect"
            bluetoothctl disconnect ${device[${DEV}]} &> /dev/null
            if [[ $audio_device[*] =~ $DEV ]]; then
                echo "Change audio out"
                pactl set-default-sink "alsa_output.pci-0000_65_00.6.analog-stereo "
            fi
        ;;
        "r" | "reconnect")
            bluetoothctl disconnect ${device[${DEV}]} &> /dev/null
            if [[ $? != 0 ]]; then
                MSG="disconnect"
                return 1
            fi
            MSG="reconnect"
            bluetoothctl connect ${device[${DEV}]} &> /dev/null
            pactl set-default-sink "bluez_output.$PACTL_DEV.1"
        ;;
        *)
            echo -e "${RED}Invalid command. Expected: connect, disconnect or reconnect${NC}"
            if [[ $audio_device[*] =~ $DEV ]]; then
                pactl set-default-sink "bluez_output.$PACTL_DEV.1"
            fi
            return 1
    esac

    if [[ $? == 0 ]]; then
        echo -e "${GREEN}Successful ${MSG} to ${DEV_NAME}${NC}"
    else
        echo -e "${RED}Cannot ${MSG} to ${DEV_NAME}${NC}"
    fi
}
