#! /usr/bin/env bash

tex-create(){
    local TEX_TEMPLATES=$HOME/.config/tex
    local DESTINATION=$PWD
    local DOC_TYPE="RAPORT"
    local VERTICAL_PAGE=false
    local BIBLIOGRAPHY=false
    local OVERWRITE=false

    while getopts ":rpvbnt" opt; do
        case $opt in
            t)
                DOC_TYPE="TEST"
            ;;
            p)
                DOC_TYPE="PRESENTATION"
            ;;
            v)
                VERTICAL_PAGE=true
            ;;
            b)
                BIBLIOGRAPHY=true
            ;;
            n)
                OVERWRITE=true
            ;;
            *)
                echo -e "{RED}Invalid arguments{NC}"
                echo -e "Args list:"
                echo -e "\t-t -- create test"
                echo -e "\t-p -- create presentation"
                echo -e "\t-v -- add vertical pages"
                echo -e "\t-b -- add bibliography"
                echo -e "\t-n -- no overwrite"
                return 1
            ;;
        esac
    done



    local create_files(){
        if [[ -f $DESTINATION/main.tex ]]; then
            if [[ $OVERWRITE == true ]]; then
                return 0
            elif ( ! confirm "${RED}Overwrite files?${NC}" ); then
                return 1
            fi
            echo "${ORANGE}Overwrite current main files!${NC}"
        fi

        mkdir -p ${DESTINATION}/Img
        mkdir -p ${DESTINATION}/Chapters
        mkdir -p ${DESTINATION}/Measure


        cp "${TEX_TEMPLATES}/agh_logo.jpg" ${DESTINATION}/Img
        cp "${TEX_TEMPLATES}/.gitignore" ${DESTINATION}
        cp "${TEX_TEMPLATES}/justfile" ${DESTINATION}

        printf "${GREEN}LaTeX project was created: "
        case $DOC_TYPE in
            "RAPORT")
                cp "${TEX_TEMPLATES}/raport_template.tex" ${DESTINATION}/main.tex
                echo -e "${YELLOW}raport${NC}"
                ;;
            "PRESENTATION")
                cp "${TEX_TEMPLATES}/prez.tex" "${DESTINATION}/main.tex"
                cp "${TEX_TEMPLATES}/beamerthemeAGH.sty" "${DESTINATION}"
                cp "${TEX_TEMPLATES}/beamercolorthemeAGH.sty" "${DESTINATION}"
                echo -e "${YELLOW}presentation${NC}"
                ;;
            "TEST")
                cp "${TEX_TEMPLATES}/test_template.tex" "${DESTINATION}/main.tex"
                echo -e "${YELLOW}test${NC}"
                ;;
        esac
    }

    local addBibliography(){
        FILE="${DESTINATION}/main.tex"

        ADD_TO_MAIN="\n"
        ADD_TO_MAIN+="\\\usepackage[polish]{babel}\n"
        ADD_TO_MAIN+="\\\usepackage{csquotes}\n"
        ADD_TO_MAIN+="\\\usepackage[sorting=none]{biblatex}\n"
        ADD_TO_MAIN+="\\\bibliography{bibliography.bib}\n"

        if [[ ! ( -e $FILE ) ]]; then
            echo -e "${RED}File main.tex not exist${NC}"
            echo -e "Remember to add ${ORANGE}${ADD_TO_MAIN}${NC} in your main.tex"
        else
            if grep -Fxq '\bibliography{bibliography.bib}' "$FILE"; then
                echo -e "${YELLOW}Latex currently use bibliography${NC}"
                return 0
            fi

            LINE=$(awk '/^$/{print NR; exit}' "$FILE")
            # sed -i "/^$/ {s/^$/$ADD_TO_MAIN/; :a;n;ba}" "$FILE"
            sed -i "${LINE}s/^$/$ADD_TO_MAIN/" "$FILE"

            echo -e "${GREEN}Add bibliography in line ${LINE}${NC}"
            touch bibliography.bib
        fi
    }



    create_files
    if [[ $BIBLIOGRAPHY ]]; then
        addBibliography
    fi

}
